### ISSUE TITLE
Can't install on SB 3.2

### ISSUE THREAD

**Issue by Back-Sephiroth** [mjmlio/mjml-syntax#12]
Hello, 

This package is not shown on my sublimeText package control. 

So i'd tried to install it manually, in my packages folder, and when i start sublime Text the package is automatically removed.

My sublime text version is 3.2 build 3200

Regards

**Comment by ngarnier** [comment]
Hey, do you mean it's not listed when trying to install a package via the command palette? That would be strange because it's properly listed here: https://packagecontrol.io/packages/MJML-syntax.

Are you sure it's not already installed? Can you reproduce a video like this: http://recordit.co/7AFl3DKekq? You can see that I don't have it listed but simply because it's already installed.

**Comment by Back-Sephiroth** [comment]
Sorry, 

Indeed, the package was installed, but I did not find it in my folder and the code was not interpreted.

So I reinstalled the package and everything works.
